modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="apicraft"
version="${mod_version}"
#version="0.0.1"
displayName="Apicraft"
#logoFile="forestry_logo.png"
credits="TeamCofh and ForestryMC Team"
authors="Emily Crystal for sourcecode."
description='''
An apiculture addon for Cofh series, aimed to bring Apiculture in the ForestryMC and APICO to 1.19+.
'''

[[dependencies.apicraft]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.apicraft]]
    modId="cofh_core"
    mandatory=true
    versionRange="[11.0.0,11.3.0)"
    ordering="NONE"
    side="BOTH"
[[dependencies.apicraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.3)"
    ordering="NONE"
    side="BOTH"
